### ISSUE TITLE
Update Lucid dependency

### ISSUE THREAD

**Issue by maukoese** [verful/notifications#1]
First of all, thank you for this package, I almost started working on my own implementation.

Could you please update the @adonisjs/lucid dependency for this packake to ^17...?. Installation fails cause I have the latest version.

**Comment by segungreat** [comment]
I face same issue here

**Comment by arthur-er** [comment]
Fixed in [v2.0.1](https://github.com/verful/notifications/releases/tag/v2.0.1)

**Comment by maukoese** [comment]
Awesome, thank you.

**Comment by maukoese** [comment]
Not sure if I should open another issue for this but kindly check @adonisjs/mail version as well.
